---
# tasks file for nginx-settings

- name: Check Linux distibutive
  debug: var=ansible_os_family

- block: # =======Block for Ubuntu=======

  - name: Update package list
    apt: cache_valid_time=3600 update_cache=yes

  - name: Install Nginx
    apt: name=nginx state=latest

  - name: Autostart webserver
    service: name=nginx state=started enabled=yes

  when: ansible_os_family == "Debian"


- block: # =======Block for Redhat=======

  - name: Install epel-release
    yum: name=epel-release state=latest
 
  - name: Install Nginx
    yum: name=nginx state=latest

  - name: Autostart webserver
    service: name=nginx state=started enabled=yes

  when: ansible_os_family == "RedHat"

